config/routes.rb
Geizer::Application.routes.draw do
  resources :messages

  resources :filters

  resources :systems

  resources :clients

  match '/',		:to => 'clients#index'

  root :to => 'clients#index'

end

app/models/system.rb
#encoding: utf-8
class System < ActiveRecord::Base
  HUMAN_ATTRIBUTE_NAMES = {
    :name => 'Наименование'  
  }
  class << self
    def human_attribute_name attribute_name
      HUMAN_ATTRIBUTE_NAMES[attribute_name.to_sym] || super
    end
  end


  has_and_belongs_to_many :filters
  has_and_belongs_to_many :clients

end

app/controllers/systems_controller.rb
#encoding: utf-8
class SystemsController < ApplicationController
  # GET /systems
  # GET /systems.json
  def index
    @systems = System.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @systems }
    end
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
    @system = System.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @system }
    end
  end

  # GET /systems/new
  # GET /systems/new.json
  def new
    @system = System.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @system }
    end
  end

  # GET /systems/1/edit
  def edit
    @system = System.find(params[:id])
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(params[:system])

    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, notice: 'Очистительная система успешна создана.' }
        format.json { render json: @system, status: :created, location: @system }
      else
        format.html { render action: "new" }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /systems/1
  # PUT /systems/1.json
  def update
    @system = System.find(params[:id])

    respond_to do |format|
      if @system.update_attributes(params[:system])
        format.html { redirect_to @system, notice: 'Очистительная система успешна обновлена.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system = System.find(params[:id])
    @system.destroy

    respond_to do |format|
      format.html { redirect_to systems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/systems/_filters.html.erb
<h5>Фильтры</h5>
<% @system.filters.each do |filter| %>
  
    <div><%= filter.name %></div>
  
<% end %>

app/views/systems/_form.html.erb
<%= form_for(@system) do |f| %>
  <% if @system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system.errors.count, "error") %> prohibited this system from being saved:</h2>

      <ul>
      <% @system.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label System.human_attribute_name(:name) %><br />
    <%= f.text_field :name %>
  </div>

  <h2>Фильтры</h2>
  <% for filter in Filter.find(:all) %>
	<div>
		<%= check_box_tag "system[filter_ids][]", filter.id, @system.filters.include?(filter)%>
		<%= filter.name%>
	</div>

  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/systems/edit.html.erb
<h1>Очистительная система</h1>

<%= render 'form' %>

<%= link_to 'Показать', @system %> |
<%= link_to 'Назад', systems_path %>

app/views/systems/index.html.erb
<h1>Очистительные системы</h1>

<table>
  <tr>
    <th><%= System.human_attribute_name(:name) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @systems.each do |system| %>
  <tr>
    <td><%= system.name %></td>
    <td><%= link_to 'Показать', system %></td>
    <td><%= link_to 'Редактировать', edit_system_path(system) %></td>
    <td><%= link_to 'Удалить', system, confirm: 'Вы уверены?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая очистительная система', new_system_path %>

app/views/systems/new.html.erb
<h1>Новая очистительная система</h1>

<%= render 'form' %>

<%= link_to 'Назад', systems_path %>

app/views/systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= System.human_attribute_name(:name) %>:</b>
  <%= @system.name %>
</p>
<%= render 	'filters' %>

<%= link_to 'Редактировать', edit_system_path(@system) %> |
<%= link_to 'Назад', systems_path %>