config/routes.rb
Geizer::Application.routes.draw do
  resources :messages

  resources :filters

  resources :systems

  resources :clients

  match '/',		:to => 'clients#index'

  root :to => 'clients#index'

end

app/models/filter.rb
#encoding: utf-8
class Filter < ActiveRecord::Base

  HUMAN_ATTRIBUTE_NAMES = {
    :name => 'Имя',
    :resource => 'Ресурс'  
  }
  class << self
    def human_attribute_name attribute_name
      HUMAN_ATTRIBUTE_NAMES[attribute_name.to_sym] || super
    end
  end


  has_and_belongs_to_many :systems

end

app/controllers/filters_controller.rb
#encoding: utf-8
class FiltersController < ApplicationController
  # GET /filters
  # GET /filters.json
  def index
    @filters = Filter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @filters }
    end
  end

  # GET /filters/1
  # GET /filters/1.json
  def show
    @filter = Filter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @filter }
    end
  end

  # GET /filters/new
  # GET /filters/new.json
  def new
    @filter = Filter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @filter }
    end
  end

  # GET /filters/1/edit
  def edit
    @filter = Filter.find(params[:id])
  end

  # POST /filters
  # POST /filters.json
  def create
    @filter = Filter.new(params[:filter])

    respond_to do |format|
      if @filter.save
        format.html { redirect_to @filter, notice: 'Фильтр успешно создан.' }
        format.json { render json: @filter, status: :created, location: @filter }
      else
        format.html { render action: "new" }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /filters/1
  # PUT /filters/1.json
  def update
    @filter = Filter.find(params[:id])

    respond_to do |format|
      if @filter.update_attributes(params[:filter])
        format.html { redirect_to @filter, notice: 'Фильтр успешно обновлен.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.json
  def destroy
    @filter = Filter.find(params[:id])
    @filter.destroy

    respond_to do |format|
      format.html { redirect_to filters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_form.html.erb
<%= form_for(@filter) do |f| %>
  <% if @filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
      <% @filter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label Filter.human_attribute_name(:name) %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label Filter.human_attribute_name(:resource) %> (кол-во мес.)<br />
    <%= f.number_field :resource %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filters/edit.html.erb
<h1>Редактирование фильтра</h1>

<%= render 'form' %>

<%= link_to 'Показать', @filter %> |
<%= link_to 'Назад', filters_path %>

app/views/filters/index.html.erb
<h1>Фильтры</h1>

<table>
  <tr>
    <th><%= Filter.human_attribute_name(:name) %></th>
    <th><%= Filter.human_attribute_name(:resource) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @filters.each do |filter| %>
  <tr>
    <td><%= filter.name %></td>
    <td><%= filter.resource %></td>
    <td><%= link_to 'Показать', filter %></td>
    <td><%= link_to 'Редактировать', edit_filter_path(filter) %></td>
    <td><%= link_to 'Удалить', filter, confirm: 'Вы уверены?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новый фильтр', new_filter_path %>

app/views/filters/new.html.erb
<h1>Новый фильтр</h1>

<%= render 'form' %>

<%= link_to 'Назад', filters_path %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= Filter.human_attribute_name(:name) %>:</b>
  <%= @filter.name %>
</p>

<p>
  <b><%= Filter.human_attribute_name(:resource) %>:</b>
  <%= @filter.resource %>
</p>


<%= link_to 'Редактировать', edit_filter_path(@filter) %> |
<%= link_to 'Назад', filters_path %>