config/routes.rb
Geizer::Application.routes.draw do
  resources :messages

  resources :filters

  resources :systems

  resources :clients

  match '/',		:to => 'clients#index'

  root :to => 'clients#index'

end

app/views/layouts/_footer.html.erb
<footer>
<div >
		<hr>
		<div class="left" id="footer-left">	
			<table><tr><td>			
				
			</td></tr></table>
				
				<noindex>	
					<!-- reformal.ru -->
						<script type="text/javascript"><!--
					reformal_wdg_domain    = "geizer";
					reformal_wdg_mode    = 0;
					reformal_wdg_title   = "Geizer-Хабаровск";
					reformal_wdg_ltitle  = "Оставьте свой отзыв";
					reformal_wdg_lfont   = "";
					reformal_wdg_lsize   = "";
					reformal_wdg_color   = "#b8d997";
					reformal_wdg_bcolor  = "#516683";
					reformal_wdg_tcolor  = "#FFFFFF";
					reformal_wdg_align   = "right";
					reformal_wdg_charset = "windows-1251";
					reformal_wdg_waction = 0;
					reformal_wdg_vcolor  = "#9FCE54";
					reformal_wdg_cmline  = "#E0E0E0";
					reformal_wdg_glcolor  = "#105895";
					reformal_wdg_tbcolor  = "#FFFFFF";
					 
					reformal_wdg_bimage = "7688f5685f7701e97daa5497d3d9c745.png";
					 //-->
					</script>
					
					<script type="text/javascript" language="JavaScript" src="http://widget.reformal.ru/tab6.js"></script><noscript><a href="http://smsfeedback.reformal.ru">SMSfeedback feedback </a> <a href="http://reformal.ru"><img src="http://reformal.ru/i/logo.gif" alt=""/></a></noscript>

					<!-- reformal.ru -->
					</noindex>	

			<div class="clearer">&nbsp;</div>

		</div>

		<div class="right" id="footer-right">

			<p class="vcard">			
			
					<br/></p>
					<div class="vcard">
					<div class="fn org"> &nbsp;&nbsp;<noindex><a ref="nofollow" href="mailto://mgerasim@inbox.ru">Поддержка</a></noindex></div>
				</div>			
			<nobr> <a href="#top" class="quiet">Вернуться наверх &uarr;</a> </nobr>
		</div>

		<div class="clearer">&nbsp;</div>

	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div id="header">
		<div id="top">		
			<div class="span-6 colborder" >
				Гейзер
			</div>
			<div class="span-16 last">
			
				<ul class="alt">
					Обратная связь с клиентами – это основа и будущее успешного бизнеса
				</ul>
				<div class="clearer">&nbsp;</div>
			</div>
			<div class="clearer">&nbsp;</div>
		</div>
		<nav>
		
			<%= render 'layouts/menu'%>
			

			


			<div class="clearer">&nbsp;</div>

		</nav>

	</div>
</header>

app/views/layouts/_menu.html.erb

<em><ul class="span-24 last tabbed">
<li>				<strong><%= link_to 'Клиенты', clients_path %></strong>                    </li>
<li>				<strong><%= link_to 'Очистительные системы', systems_path %></strong> </li>
<li>				<strong><%= link_to 'Фильтры', filters_path %></strong></li>
<li>				<strong><%= link_to 'Сообщения', messages_path %></strong></li>
</ul></em>
 

app/views/layouts/_siderbar.html.erb
<ol>
	<%= link_to 'Клиенты', clients_path %>
	<%= link_to 'Очистительные системы', systems_path %>
	<%= link_to 'Фильтры', filters_path %>
	<%= link_to 'Сообщения', messages_path %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <title>application.html</title>	  	
	  <%= javascript_include_tag "application" %>
<!-- Framework CSS -->
	
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>

    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %><![endif]-->
    <style type="text/css" media="screen">
      p, table, hr, .box { margin-bottom:25px; }
      .box p { margin-bottom:10px; }
    </style>

    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
    
    <%= csrf_meta_tag %>

  </head>
  
  <body>
	<div class="container">	
		<%= render 'layouts/header'%>
		
		<div class="span-24 first">
			<%= yield %>
		</div>
		
		<%= render 'layouts/footer'%>
  	</div> 	
  </body>
</html>